---
- name: playbook2
  hosts: localhost
  vars:
    usernames:
      - gunjan
      - olanike
      - Adebimpe
      - Abayomi


  tasks:
    - name: run command
      command: echo "hi"
      register: contents
      tags:
        - webservers



    - name: run task on basis of previous successful run
      command: echo "success"
      when: contents.stdout.find('hello')!=-1

    - name: run task on basis of previous successful changes
      command: echo "success"
      when: contents.changed == 'true'


    - name: echo usernames
      command: 'echo "{{ items }}"'
      with_items: '{{ usernames }}'




