---
- name: playbook2
  hosts: localhost
  vars:
    usernames:
      - gunjan
      - olanike
      - Adebimpe
      - Abayomi


  tasks:
    - include_vars: vars.yml
    - name: run command
      command: echo "hi"
      register: contents
      tags:
        - webservers



    - name: run task on basis of previous successful run
      command: echo "success"
      when: contents.stdout.find('hello')!=-1

    - name: run task on basis of previous successful changes
      command: echo "success"
      when: contents.changed == 'true'


    - name: running loop
      command: echo {{ item }}
      loop:
        - oladimeji
        - olajumoke
        - olanike
        - Jayden

    - name: create username
      user: name='{{ item }}' state=present
      loop:
        - oladimeji
        - olajumoke
        - olanike
        - Jayden


    - name: create username
      command: echo'{{ item }}'
      with_item: '{{ username }}'

