---
- name: hello world
  hosts: localhost
  vars:
    car_model: 'BMW M3'
    country_name: USA
    title: 'Systems Engineer'
    dns_server: 192.168.0.29


  tasks:
    - name: display hello world
      shell: echo "hello world"

    - name: display date
      command: date

    - name: list files
      command: ls -lart
      args:
        chdir: /etc/ansible

    - name: Add line to text file
      lineinfile:
        path: /root/test.txt
        line: 'server 192.168.0.46'

    - name: Add Ip to dns
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{ dns_server }}'


    - name: Car model
      command: 'echo " My car model is {{car_model}}"'

    - name: Country Name
      command: 'echo " My country is {{country_name}}"'

    - name: Job title
      command: 'echo " My job is {{title}}"'

