---

- name: Install and configure tomcat server for deployment
  hosts: webservers
  remote_user: root

  vars:
    tomcat_user: tomcat
    tomcat_path: /opt/tomcat

  tasks:
    - name: update system package
      yum:
        update_only: yes
        update_cache: yes
        state: latest

    - name: install Java
      yum:
        name: java-11-openjdk-devel
        state: present

    - name: create Tomcat user
      user:
        name: '{{ tomcat_user}}'

    - name: create Tomcat group
      group:
        name: '{{ tomcat_user }}'

    - name: create tomcat directory
      file:
        path: '{{ tomcat_path}}'
        owner: '{{ tomcat_user }}'
        group: '{{ tomcat_user}}'
        mode: 755
        recurse: yes

    - name: Download Tomcat and unarchive
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
        dest: '{{ tomcat_path }}'
        remote_src: yes
        validate_certs: no
        extra_opts: [ --strip-components=1 ]

    - name: Start tomcat server
      command: nohup {{ tomcat_path }}/bin/startup.sh

    - name: allow tcp connections
      command: sudo ufw allow 8080/tcp

    - name: connect to tomcat on port 8080
      tags:
        - test
        - connect
      uri:
        url: http://localhost:8080
      register: result
      until: "result.status==200"
      retries: 2
      delay: 5
      notify:
        - Echo connection

  handlers:
    - name: Echo connection
      command: echo "success"